server:
  port: 8002
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.ycx.lend.pojo
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  configuration:
    log-impl:
      pagehelper: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    learning: debug
spring:
  application:
    name: car-lending
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp12gjcylbvar819iao.mysql.rds.aliyuncs.com:3306/ycx?charset=utf-8&useUnicode=true&useSSL=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
      username: ycx
      password: Zjgf6666
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    maxTotal: 1000
    database: 0
    host: hadoop100
    port: 6379
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka