server:
  port: 1112
spring:
  application:
    name: security-boot-start

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
feign:
  compression:
    request:
      min-request-size: 10240